# Generated by Django 5.0.6 on 2024-06-11 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_2_app', '0002_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sticky_notes_2_app.colour'),
        ),
    ]
