# Generated by Django 5.0.6 on 2024-06-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_2_app', '0003_note_note_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_colour',
            new_name='colour',
        ),
    ]
